import Head from 'next/head'
import Header from '../components/Header'
import HeroImage from '../components/HeroImage'
import axios from 'axios'
import SmallCard from '../components/SmallCard'
import MediumCard from '../components/MediumCard'

export default function Home({ exploreData, liveData }) {
  console.log(exploreData)
  return (
    <div className='min-h-screen'>
      <Head>
        <title>Airbnb clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <HeroImage />

      <main className='my-5 max-w-7xl mx-auto px-8'>
        <section>
          <h2 className='text-2xl font-bold mb-5'>Explore nearby</h2>
          <div className='grid sm:grid-cols-2 lg:grid-cols-4'>
            {exploreData?.map(({ img, location, distance }) => (
              <SmallCard
                key={location}
                img={img}
                location={location}
                distance={distance} />
            ))}
          </div>
        </section>

        <section className='mt-5 '>
          <h2 className='text-2xl font-bold mb-5'>Live Anywhere</h2>
          <div className='flex overflow-scroll space-x-3 no-scrollbar '>

            {liveData?.map(({ img, title }) => (
              <MediumCard key={title} img={img} title={title} />
            ))}
          </div>

        </section>
      </main>


    </div>
  )
}

export async function getStaticProps() {
  const exploreRes = await axios.get('https://links.papareact.com/pyp')
  const liveRes = await axios.get('https://links.papareact.com/zp1')
  // console.log(res.data)
  return {
    props: {
      exploreData: exploreRes.data,
      liveData: liveRes.data
    }, // will be passed to the page component as props
  }
}