import Head from 'next/head'
import Header from '../components/Header'
import HeroImage from '../components/HeroImage'

export default function Home() {
  return (
    <div className='min-h-screen'>
      <Head>
        <title>Airbnb clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <HeroImage />


    </div>
  )
}
